server:
    port: 8080

eureka:
    instance: 
        hostname: localhost

spring:
    application:
        name: api-gateway
    cloud:
        gateway:
            routes:
                - id: first-route
                  uri: http://localhost:8081 # rota fixa
                  predicates:
                    - Path=/first/**
                - id: second-route
                  uri: lb://second-service
                  predicates:
                    - Path=/second/**
